mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


spring:
  application:
    name: tlias-web-management
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 5MB

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

aliyun:
  oss:
    endpoint: http://oss-cn-hangzhou.aliyuncs.com
    bucketName: web-tlias-zehuang
    region: cn-hangzhou


